config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users
  resources :tricks do
  	member do
  		get "like", to: "tricks#upvote"
  		get "dislike", to: "tricks#downvote"
  	end
  	resources :comments
  end

  root 'tricks#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :trick
  belongs_to :user
end

app/models/trick.rb
class Trick < ActiveRecord::Base
	belongs_to :user
	  has_attached_file :image, styles:  { medium:  "500x500#", thumb:  "100x100#" }
  validates_attachment_content_type :image, content_type:  /\Aimage\/.*\Z/
  has_many :comments
  acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


    has_many :tricks
    has_many :comments
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  	devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def create
		@trick = Trick.find(params[:trick_id])
		@comment = Comment.create(params[:comment].permit(:content))
		@comment.user_id = current_user.id
		@comment.trick_id = @trick.id

		if @comment.save
			redirect_to trick_path(@trick)
		else
			render 'new'
		end
	end
end

app/controllers/tricks_controller.rb
class TricksController < ApplicationController
	before_action :find_trick, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@tricks = Trick.all.order(:cached_votes_up => :desc)
	end
	
	def show
		@comments = Comment.where(trick_id: @trick)
	end

	def new
		@trick = current_user.tricks.build
	end

	def create
		@trick = current_user.tricks.build(trick_params)

		if @trick.save
			redirect_to @trick
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @trick.update(trick_params)
			redirect_to @trick
		else
			render 'edit'
		end
	end

	def destroy
		@trick.destroy
		redirect_to root_path
	end


	def upvote
		@trick.upvote_by current_user
		redirect_to root_path
	end

	def downvote
		@trick.downvote_by current_user
		redirect_to root_path
	end

	private

	def find_trick
		@trick = Trick.find(params[:id])
	end

	def trick_params
		params.require(:trick).permit(:title, :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tricks_helper.rb
module TricksHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for([@trick, @trick.comments.build]) do |f| %>
  <p>  
    <%= f.input :content, label: "Reply to trick" %> 
  </p>  
  <p><%= f.submit %></p>  
<% end %> 

app/views/layouts/_nav.html.erb
 
 <div class="navbar">
 
          <!-- Navbar inner for Index page-->
          <div data-page="index" class="navbar-inner">
          <div class="left">
            <!-- Right link contains only icon - additional "icon-only" class--><a href="#" class="link icon-only open-panel"> <i class="icon icon-bars"></i></a>
            
          </div>
            <!-- We have home navbar without left link-->
            <div class="center sliding">Spotking</div>
            <div class="right">
            <div class="right">
            <%= link_to "Sign-in", new_user_session_path %>
            </div>

            <%= link_to "Sign-out", destroy_user_session_path, :method => :delete, class: 'fa fa-sign-out fa-2x' %>
            </div>
              </a>
            </div>
          </div>


        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spot8</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/tricks/_form.html.erb
<%= simple_form_for @trick do |f| %>
  <p>  
    <%= f.input :image %>  
    <%= f.label :title %>  
    <%= f.text_field :title %>  
  </p>  
  <p><%= f.submit %></p>  
<% end %> 

app/views/tricks/edit.html.erb
Edit

<%= render 'form'  %>

app/views/tricks/index.html.erb
<% @tricks.each do |trick| %>
<%= link_to(image_tag trick.image.url(:thumb)) %>
  <br/>
  <tr>
    <td><%= link_to trick.title, trick %></td>
  </tr>
   <br/>
  <tr>
    <td><%= link_to trick.user.name, trick %></td>
  </tr>
  <br/>
<%= trick.get_upvotes.size %>
<%= link_to("like", trick , method: :get) %>
<br/>
<%= trick.get_downvotes.size %>
<%= link_to("dislike", trick , method: :get) %>

  <br/>
  <tr>
    <td><%= link_to trick.comments.count, trick %> Comments</td>
  </tr>
  <br/>
    <br/>
<% end %>
</table>
  <br/>
<%= link_to("New Trick", new_trick_path) %>

app/views/tricks/new.html.erb
<h1>Add New Trick</h1>

<%= render 'form' %>


<%= link_to("Back", root_path) %>

app/views/tricks/show.html.erb
<%= image_tag @trick.image.url(:medium) %>
<%= @trick.title %> -
<%= @trick.user.name %>
<br/>
<%= @trick.get_upvotes.size %>
<%= link_to("like", like_trick_path(@trick) , method: :get) %>
<br/>
<%= @trick.get_downvotes.size %>
<%= link_to("dislike", dislike_trick_path(@trick) , method: :get) %>


<br/>
<%= pluralize(@trick.comments.count, "Comment") %>
</h2>
<% @comments.each do |comment| %>
<div class="comment">
  <p class="username">
    <%= comment.user.name %>
  </p>
  <p class="content">
    <%= comment.content %>
  </p>
</div>
<% end %>

<%= render 'comments/form' %>
<br/>



  <tr>
    <td><%= link_to "Edit", edit_trick_path(@trick) %></td>
    <td><%= link_to "Remove", @trick, method: :delete, data: { confirm: "Are you sure?" } %></td>
  </tr>
  <br/>
<%= link_to("Back", root_path) %>
<%= link_to("New Trick", new_trick_path) %>